Add the ability to test CSS property values to custom-css.json
foolip/mdn-bcd-collector pull request #1805
Opened 2022-02-14 17:22 UTC by gsnedders

This also adds a lot of the more easily found values that either differ between {Chrome, Firefox, Safari} _or_ where entries already exist in BCD for them.

This almost certainly isn't quite what we want, but it's a starting point. Notably this produces significant changes to BCD data, as (unsurprisingly) plenty of this data is outdated.

Fixes #705, based on @foolip's earlier experience with #1221.

2022-02-19 08:42 UTC, queengooborg requested changes
This is a great PR, I'm enjoying this functionality and I think this is a great way to incorporate it!  I just have a few comments:

First, for line 838, we no longer have `propertySet` as a variable, so we'll need to do the following instead:
```js
for (const name of Array.from(properties.keys()).sort()) {
```

Second, I think that this test code should be thrown into `harness.js` and called via `bcd.testCSSProperty()`.  Since we're injecting this code so many times for each variation, the codeblock gets pretty big (about a half a page long).  I feel it would be helpful to put this into a reusable function!

2022-02-19 18:18 UTC, gsnedders commented
> This is a great PR, I'm enjoying this functionality and I think this is a great way to incorporate it! I just have a few comments:
> 
> First, for line 838, we no longer have `propertySet` as a variable, so we'll need to do the following instead:
> 
> ```js
> for (const name of Array.from(properties.keys()).sort()) {
> ```

…did I not commit before pushing? 🤦

> Second, I think that this test code should be thrown into `harness.js` and called via `bcd.testCSSProperty()`. Since we're injecting this code so many times for each variation, the codeblock gets pretty big (about a half a page long). I feel it would be helpful to put this into a reusable function!

Ah, this is the sorta feedback I was looking for! 

Looking at this again (sorry, I wrote it a while ago!), how do you feel about prefixes or what we should do with prefixes? Being able to go from something marked as supported with a prefix to being able to fill in its sub-values would be valuable, but I don't know it really makes sense to generate them for everywhere. One option would be to just generate tests for `-x-foo` if `-x-foo` exists in `custom-css.json` (i.e., append all the values into it).

2022-02-21 11:41 UTC, queengooborg commented
> Looking at this again (sorry, I wrote it a while ago!), how do you feel about prefixes or what we should do with prefixes?

Prefixes was something that we'd been looking into.  Currently, with APIs, our method is to add custom IDL with the prefixes, essentially treating prefixed interfaces/members as separate entities, to then resolve later in update-bcd.  Perhaps we could/should do something similar here?  @foolip, what do you think?

2022-02-21 16:14 UTC, foolip commented
For prefixed properties, I think we should generate separate tests and let the updater connect the dots. For prefixed property values, I guess we would add those as custom tests?

2022-02-21 23:59 UTC, gsnedders commented
> For prefixed properties, I think we should generate separate tests and let the updater connect the dots. For prefixed property values, I guess we would add those as custom tests?

but add them all explicitly, rather than implicitly?

2022-02-24 21:08 UTC, gsnedders commented
> Second, I think that this test code should be thrown into `harness.js` and called via `bcd.testCSSProperty()`. Since we're injecting this code so many times for each variation, the codeblock gets pretty big (about a half a page long). I feel it would be helpful to put this into a reusable function!

Done this now!

> > For prefixed properties, I think we should generate separate tests and let the updater connect the dots. For prefixed property values, I guess we would add those as custom tests?
> 
> but add them all explicitly, rather than implicitly?

And done this too!

2022-03-15 06:39 UTC, queengooborg approved these changes
Thank you for your hard work on this, this is LGTM!  👍

2022-03-15 06:39 UTC, merged

2022-04-22 09:08 UTC, foolip commented on custom-css.json
> -    "custom-property": {},
This removed a custom test by accident, restored in https://github.com/foolip/mdn-bcd-collector/pull/1945.